var uniquID;
$(document).ready(function() { 
  /*  $("input[title='EventTitle Required Field']").hide();
    $("input[title='EventType']").css("display","none");
    $("input[title='EventDescription']").css("display","none");
    $("input[title='Pillar']").css("display","none");
    //$("input[title='EventDescription']").hide();
    $("input[title='EventEndTime']").css("display","none");
    $("input[title='EventLink']").css("display","none");
    $("input[title='EventSpeakerName']").css("display","none");
   	$("input[title='EventOrganizerName']").css("display","none");
   	$("input[title='EventKeywords']").css("display","none");
	$("input[title='Status']").css("display","none");
	$("input[title='EventSubtitle']").css("display","none");
	$("input[title='ID']").css("display","none");
	$("input[title='Excited']").css("display","none");
	$("input[title='NotExcited']").css("display","none");
	$("input[title='NotSure']").css("display","none");
	$("textarea[title='EventDescription']").css("display","none");
    $("input[title='EventStartTime']").css("display","none");
	$("input[title='EventDate']").css("display","none");
    $('#Title').css("display","none");
    $('#EventType').css("display","none");
    $('#Pillar').css("display","none");
	$('#EventDescription').css("display","none");
	$('#EventDate').css("display","none");
	$('#EventStartTime').css("display","none");
	$('#EventEndTime').css("display","none");
	$('#EventLink').css("display","none");
	$('#EventSpeakerName').css("display","none");
	$('#EventOrganizerName').css("display","none");
	$('#EventKeywords').css("display","none");
	$('#Status').css("display","none");
	$('#EventSubtitle').css("display","none");
	$('#Exited').css("display","none");
	$('#NotExcited').css("display","none");
	$('#NotSure').css("display","none");
	$('#AutoPublishDateTime').css("display","none");
	$('#Attachments').css("display","none");
	$('#ID0').css("display","none");
    $('#s4-ribbonrow').css("display","none");
    $(".ms-dtinput").css("display","none");
    $(".ms-dttimeinput").css("display","none"); 
    $(".ms-dlgTitle").css("background-color", "yellow");*/
    $('#s4-ribbonrow').css("display","none");
		$("#part1 > table.ms-formtable > tbody > tr").attr("style","display:none");
        $("#part1 > table.ms-formtable > tbody > tr:nth-child(14)").attr("style","display:block !important;");
    $("input[value$='Save']").attr('value', "Share");
    
 });
